### ISSUE TITLE
NPM or yarn

### ISSUE THREAD

**Issue by tgrecojs** [nitin42/React-AR#3]
This may be SUPER minor but I figured that it was worth bringing up.

I see that this relies on yarn but then in the installation it is suggested to use npm. to my knowledge, yarn can be used in place of npm to better manage packages. since the project comes with a yarn.lock file I figured that it was probably best practice to use the `yarn add` command as opposed to `npm i`.

again, i know it's super minor but since you're the creator of the project and you utilize yarn, it may be wise to suggest this to users 😄

**Comment by nitin42** [comment]
Though I use yarn on my system, I thought to recommend npm also. But ya you're right that we should place instructions for yarn only (since we have yarn.lock file). I'll make the changes 👍
